import Head from "next/head";
import MainPage from "@/components/MainPage";
import Companies from "@/components/Company";
import Guide from "@/components/Guide";
import Properties from "@/components/Properties";
import Details from "@/components/Details";
import GetStarted from "@/components/GetStarted";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPage />
        <Companies />
        <Guide />
        <Properties />
        <Details />
        <GetStarted />
        <Footer />
      </main>
    </>
  );
}
